# Generated by Django 3.2.7 on 2021-09-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('replies', models.CharField(max_length=100)),
            ],
        ),
    ]
