# Generated by Django 3.2.7 on 2021-09-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeApp', '0002_auto_20210915_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='videoId',
            field=models.TextField(max_length=20),
        ),
    ]
